<h2>Cadastro de usuário</h2>
<hr/>
<form name="loginform" method="POST">
        
        <label>Nome
            <input type="text" name="nome" alt="Nome" align="left" required/>
        </label>
        <br/>
        <label>Email
            <input type="email" name="email" alt="Email" align="left" required/>
        </label>
        <br/>
        <label>Senha
            <input type="password" name="senha" alt="Senha" align="left" required/>
        </label><br/>
        <input class="btn btn-success" style="vertical-align:baseline;" type="submit" value="Cadastrar"/>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/usuario'); ?>">Voltar</a>
</form>
<br/><br/><br/><br/>