<h2>Editar de usuário</h2>
<hr/>

<form name="loginform" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->usuario->id?>">
        <label>Nome
            <input type="text" name="nome" value="<?php echo $this->usuario->nome?>" alt="Nome" align="left" required/>
        </label>
        <br/>
        <label>Email
            <input type="email" name="email" value="<?php echo $this->usuario->email?>" alt="Email" align="left" required/>
        </label>
        <br/>
        <label>Senha
            <input type="password" name="senha" value="<?php echo $this->usuario->senha?>" alt="Senha" align="left" required/>
        </label><br/>
        <input class="btn btn-success" style="vertical-align:baseline;" type="submit" value="Editar"/>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/usuario'); ?>">Voltar</a>
</form>
<br/><br/><br/><br/><br/><br/><br/>