<h2>Gerenciar usuários</h2>
<hr/>
<a class="btn btn-info" href="<?php echo $this->baseUrl('/usuario/cadastrar')?>">
Cadastrar usuário
</a>
<br/><br/>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>
    <?php foreach ($this->array as $value) :?>
    <tr>
        <td><?php echo $value['id']?></td>
        <td><?php echo $value['nome']?></td>
        <td>
            <a class="btn btn-warning" href="<?php echo $this->baseUrl('/usuario/editar/id/'.$value['id'])?>">
            Editar
            </a>            
            <a class="btn btn-danger" href="<?php echo $this->baseUrl('/usuario/excluir/id/'.$value['id'])?>">
            Excluir
            </a>            
        </td>                  
    </tr>
    <?php endforeach;?>
</table>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>