<h1 style="color:gray;">Cadastro de Projeto</h1><br /><hr /><br /><br />


<form name="signup" method="post" action="cadastrandoColaborador.php">
    <article>
        <label>Nome do Projeto</label><br/>
        <input type="text" name="nomeProjeto" alt="Nome do Projeto" align="left" required/>
        <br/><br/>
        <label>Responsável</label><br/>
        <input type="text" name="cargo" alt="email" align="left" required/>
        <br/><br/>
        <label>Resultado</label><br/>
        <input type="text" name="resultado" alt="resultado" align="left" required/>
        <br/><br/>
        <div><label>Data de Início</label><br/>
            <input type="date" name="inicio" alt="inicio" align="left" /></div>
        </div><br/><br/>
        <div><label>Data de conclusão</label><br/>
            <input type="date" name="conclusao" alt="conclusao" align="left" /></div>
        </div><br/><br/>

        <input type="submit" value="Enviar"/>		<input type="reset" class="reset" value="Limpar"/>
    </article>					
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>