<form name="loginform" method="POST" action="<?php echo $this->baseUrl("/colaborador"); ?>">
         <br/>
        <input type="email" name="email" alt="Email" align="left" placeholder="Email"required/>
        <br/><br/>  
        <input type="password" name="senha" alt="Senha" align="left" placeholder="Senha" required/>
        <br/><a href="#"><h6 style="color: #FFF;" >Esqueci a Senha</h6></a>
        <input type="submit" class="btn btn-toolbar" value="Entrar"/>
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>