<form name="loginform" method="POST" action="<?php echo $this->baseUrl("/colaborador"); ?>">
        <label>Email</label><br/>
        <input type="email" name="email" alt="Email" align="left" required/>
        <br/><br/>
        <label>Senha</label><br/>
        <input type="password" name="senha" alt="Senha" align="left" required/>
        <br/><a href="#" ><h6>Esqueci a Senha</h6></a><br/><br/>
        <input type="submit" value="Entrar"/>
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>