
<section id="navegacao">
<h2>Editar colaborador</h2>
<hr/>
<form name="loginform" method="POST">      
    <article>
        <input type="hidden" name="id" value="<?php echo $this->colaborador['id']?>">    
        <input type="hidden" name="usuario_id" value="<?php echo $this->colaborador['usuario_id']?>">    
        <label>
            <?php echo $this->colaborador['nome']?>
        </label>
        <br/>
        <label>Cargo
            <?php echo $this->formSelect('cargo',$this->colaborador['cargo'],array(),$this->cargo);?>        
        </label>
        <br/>
        <label>Matrícula
            <input type="text" name="matricula" value="<?php echo $this->colaborador['matricula']?>" alt="matricula" align="left" required/>      
        </label>
        <br/>        
        
        <div><label>Data de Admissão
            <input type="text" name="data_adm" value="<?php echo $this->colaborador['data_adm']?>" alt="data_adm" align="left" required/>      
        </label></div>
        
        <div><label>Data de Demissão
            <input type="text" name="data_dem" value="<?php echo $this->colaborador['data_dem']?>" alt="data_dem" align="left" required/>
        </label></div>
        
    </article>
        
    <article>   
        <label>Função
            <?php echo $this->formSelect('funcao',$this->colaborador['funcao'],array(),$this->funcao);?>        
        </label>
        <br/>
        <label>Area
            <?php echo $this->formSelect('area',$this->colaborador['area'],array(),$this->area);?>
        </label>
        <br/>        
         <label>Formação
            <?php echo $this->formSelect('formacao',$this->colaborador['formacao'],array(),$this->formacao);?>
         </label>
        <br/>   
    
        <input class="btn btn-success" style="vertical-align:baseline;" type="submit" value="Alterar"/>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/colaborador'); ?>">Voltar</a>
    </article>
</form>
<br/><br/><br/><br/><br/><br/><br/>
</section>