<h2>Excluir colaborador</h2>
<hr/>

<form name="loginform" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->colaborador['id']?>">
        <input type="hidden" name="excluir" value="<?php echo $this->colaborador['id']?>">
        <label>Deseja realmente excluir o Colaborador? </label><br/>
        <?php echo $this->colaborador['nome']?>
        <br/><br/>        
        <input class="btn btn-danger" style="vertical-align:baseline;" type="submit" value="Excluir"/>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/colaborador'); ?>">Voltar</a>
</form><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>