<h2>Relação de Tarefas</h2>
<hr/>
<a class="btn btn-info" href="<?php echo $this->baseUrl('/tarefa/cadastrar')?>">
Cadastrar tarefa
</a>
<br/><br/>
<table class="table table-bordered">
    <tr>        
        <th>Descrição da Tarefa</th>
        <th>Projeto</th>
        <th>Ações</th>
    </tr>
    <?php foreach ($this->tarefa as $value) :?>
    <tr>        
        <td><?php echo $value['descricao']?></td>
        <td><?php echo $value['nome_projeto']?></td>
        <td>
            <a class="btn btn-warning" href="<?php echo $this->baseUrl('/tarefa/editar/id/'.$value['id'])?>">
            Editar
            </a>            
            <a class="btn btn-danger" href="<?php echo $this->baseUrl('/tarefa/excluir/id/'.$value['id'])?>">
            Excluir
            </a>            
        </td>                  
    </tr>
    <?php endforeach;?>
</table>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>