<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
    <head>
        <title>People</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="People"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>	
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
        <link rel="sitemap" type="application/xml" title="Sitemap" href="sitemap.xml"/>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php
        echo $this->headLink()->appendStylesheet($this->baseUrl() . '/library/bootstrap/css/bootstrap.css');
        echo $this->headLink()->appendStylesheet($this->baseUrl() . '/library/bootstrap/css/bootstrap-responsive.css');
//        echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery.alerts.css');
        echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/estilos.css');
        ?>    
        <script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl(); ?>/js/lib/jquery-1.7.1.js" ></script>    
        <script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl(); ?>/js/bootstrap.js" ></script>            
    </head>
    <body>
        <section id="conteudo"> 

            <header>
                <h1>
                    <a href="index.php" style="text-decoration:none; color: black;">
                        <img  alt="logomarca" src="/tcc/public/img/logo.png"/>People</a>
                </h1>

                <nav alt="menu">
                    <ul>
                        <a href="home.php"><li>Início</li></a>
                        <a href="#"><li>Cadastro</li></a>
                        <a href="home.php"><li>Relatórios</li></a>
                        <a href="#"><li>Sair</li></a>
                    </ul>	
                </nav>
            </header>
            
            <?php if(isset($this->mensagem)) {
                echo $this->mensagem;
            }
            ?>

            <section id="navegacao">

                <?php echo $this->layout()->content; ?>



            </section><!------------- final de section navegacao ----------->

            <footer>
                &copy2014

            </footer>

        </section><!------------- final de section conteudo ------------>

    </body>
</html>
