<div class='left'>
    <label form="ddd">DDD</label>
    <?php
    echo $this->formHidden( 'telefone[id_telefone]',  $this->telefone['id_telefone']);
    echo $this->formText( 'telefone[nu_ddd]', $this->telefone['nu_ddd']
            , array( 'id' => 'ddd', 'maxlength' => '2', 'size' => '5', 'class'=>'input-mini' ) )
    ?>
</div>
<div>
    <label for="telefone">Telefone</label>
    <?php
    echo $this->formText( 'telefone[nu_telefone]', $this->telefone['nu_telefone']
            , array( 'id' => 'numero_telefone', 'maxlength' => '9', 'size' => '10' ) )
    ?>
</div>            
  