<section id="navegacao">
<h2>Editar Projeto</h2>
<hr/>
<form name="loginform" method="POST">      
     <article>
         <input type="hidden" name="id" value="<?php echo $this->projeto['id']?>">    
        
        <label>Nome do Projeto
            <?php echo $this->formText("nome_projeto",$this->projeto['nome'],array("required"=>true))?>
        </label>
        <br/>    
        <label>Gerente
            <select name="id_colaborador">
                <?php foreach($this->rel_colaboradores as $colaborador):?>
                <option value="<?php echo $colaborador["id"]?>" <?php echo ($this->projeto['id_colaborador'] == $colaborador['id'] ? 'selected' : ''); ?>>
                <?php echo $colaborador["nome"]?>
                </option>
                <?php endforeach;?>
            </select>
        </label>
        <br/>        
        <div><label>Data de Início
            <?php echo $this->formText("data_ini",$this->projeto['data_ini'],array("required"=>true))?>                
        </label></div>
        
        <div><label>Data de Conclusão
            <?php echo $this->formText("data_fim",$this->projeto['data_fim'],array())?>
        </label></div>
        <br/>
        <label>Resultado
            <?php echo $this->formText('resultado',$this->projeto['resultado'],array());?>
        </label>
        <br/>    
        <input class="btn btn-success" style="vertical-align:baseline;" type="submit" value="Alterar"/>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/projeto'); ?>">Voltar</a>
    </article>
        
    
</form>
<br/><br/><br/><br/><br/><br/>
</section>