<h2>Excluir de usuário</h2>


        <label>Nome </label><br/>
        <?php echo $this->colaborador->nome?>
        <br/><br/> 
        <label>Cargo </label><br/>
        <?php echo $this->colaborador->cargo?>
        <br/><br/> 
        <label>Área </label><br/>
        <?php echo $this->colaborador->area?>
        <br/><br/> 
        <a href="<?php echo $this->baseUrl('/colaborador'); ?>">Voltar</a>