
<section id="navegacao">
<h2>Dados do Projeto</h2>
<p><strong>Nome do Projeto: </strong><?php echo $this->projeto['nome']?></p>
        <input type="hidden" name="id" value="<?php echo $this->projeto['id']?>">           
        <p><strong>Data de Início: </strong><?php echo $this->projeto['data_ini']?></p>
        <p><strong>Gestor: </strong><?php echo $this->projeto['nome_colaborador']?></p>
<hr/>
<form name="loginform" method="POST">  
      
    <article>    
        
        <h2>Tarefas</h2><br/>
        <h3>Em andamento</h3>
        <table class="table table-bordered">
            <tr>
                <th>Tarefa</th>
                <th>Ações</th>
            </tr>
            <?php foreach ($this->tarefas_andamento as $value) :?>
            <tr>                
                <td><?php echo $value['descricao']?></td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->baseUrl('/tarefa/ver/id/'.$value['id'])?>">
                    Detalhar
                    </a> 
                    <a class="btn btn-warning" href="<?php echo $this->baseUrl('/tarefa/editar/id/'.$value['id'])?>">
                    Editar
                    </a>            
                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/tarefa/excluir/id/'.$value['id'])?>">
                    Excluir
                    </a>            
                </td>                  
            </tr>
            <?php endforeach;?>
         </table>
        <br/>
        <h3>Concluídas</h3>
        <table class="table table-bordered">
            <tr>
                <th>Tarefa</th>
                <th>Ações</th>
            </tr>
            <?php foreach ($this->tarefas_concluidos as $value) :?>
            <tr>                
                <td><?php echo $value['descricao']?></td>
                <td>
                    <a class="btn btn-primary" href="<?php echo $this->baseUrl('/tarefa/ver/id/'.$value['id'])?>">
                    Detalhar
                    </a>                      
                </td>                  
            </tr>
            <?php endforeach;?>
         </table>
        <a class="btn btn-toolbar" style="vertical-align:baseline;" href="<?php echo $this->baseUrl('/projeto'); ?>">Voltar</a>
    </article>      
</form>
<br/><br/><br/><br/><br/><br/>
</section>